version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/johanneswuerbach/aws-secrets-manager-k8s
    steps:
      - checkout
      - run: make test
